spring :
    application:
      name: spring-microservice-cloud-config-server
    cloud:
      config:
        server:
          git:
            uri: https://github.com/techefx/environment-variable-repo.git


server:
  port: ${port:8888}